version: '3'
services:
 mosquitto:
  build: ./mosquitto
  ports:
   - "1883:1883"
  volumes:
   - "./mosquitto/code/mosquitto.conf:/etc/mosquitto/mosquitto.conf"

 dbService:
  build: ./dbService
  environment:
   - MYSQL_ROOT_PASSWORD=3u&Um%k{Jr
  ports:
   - '3306:3306'

 message_router:
  build: ./message_router
  environment:
   - MQTT_SERVER_ADDRESS=mosquitto
   - MQTT_SERVER_PORT=1883
   - PYTHONUNBUFFERED=1
  volumes:
   - "./message_router/code:/etc/usr/src/app"
  depends_on:
   - mosquitto
   - dbService


