version: '3'
services:
 virtual_vehicle:
  build: ./VehicleDigitalTwin
  image: vehicle_digital_twin
  environment:
   - MQTT_SERVER_ADDRESS=34.134.232.30
   - MQTT_SERVER_PORT=1883
   - PYTHONUNBUFFERED=1 # Este comando se utiliza para que la salida de la consola no se almacene en un buffer
  volumes:
    - "./VehicleDigitalTwin/code:/etc/usr/src/code"